public class apexDefinedDataType {    
    @AuraEnabled @InvocableVariable
    public boolean z0type_set;
    @AuraEnabled @InvocableVariable
    public String z0type;	    //folder
    @AuraEnabled @InvocableVariable
    public boolean sequencex5fid_set;
    @AuraEnabled @InvocableVariable
    public String sequencex5fid;	    //0
    @AuraEnabled @InvocableVariable
    public boolean name_set;
    @AuraEnabled @InvocableVariable
    public String name;	    //aashss
    @AuraEnabled @InvocableVariable
    public boolean id_set;
    @AuraEnabled @InvocableVariable
    public String id;	    //200674937145
    @AuraEnabled @InvocableVariable
    public boolean etag_set;
    @AuraEnabled @InvocableVariable
    public String etag;	    //0
}